/*

INSTALAÇÃO DO POSTGRESQL

CRIANDO QUERIE BÁSICAS NO POSTGRES

FILTROS NO POSTGRES

FUNÇÕES DE AGREGAÇÃO E AGRUPAMENTOS NO POSTGRES

JOINS NO POSTGRES

VIEWS NO POSTGRES

OPERAÇÕES CRUD NO POSTGRESQL

FUNÇÕES DE NÚMERO, TEXTO E DATA

SUBQUERIES

FUNCTIONS

TRANSACTIONS E PROCEDURES


    */

/*                 


ESTUDOS BANCO DE DADOS POSTGRESQL

1-CRIANDO AS TABELAS DO BD NORTHWIND
2-SELECT FROM
3-COMENTÁRIOS SQL
4-SELECT AS
5-SELECT LIMIT
6-SELECT DISTINCT
7-WHERE-FILTROS DE TEXTOS
8-WHERE-FILTROS COM NÚMEROS E DATAS
9-OPERADORES AND E OR
10-WHERE E LIKE - FILTROS ESPECIAIS COM TEXTOS
11-WHERE E IN - UMA ALTERNATIVA AOS MÚLTIPLOS ORS
12-WHERE E BETWEEN - FILTRANDO INTERVALOS
13-ORDER BY - ORDENANDO OS RESULTADOS
14-FUNÇÕES DE AGREGACAO - COUNT, SUM, AVG, MIN, MAX
15-GROUP BY - AGRUPANDO RESULTADOS
16-HAVING - FILTRANDO GRUPOS
17-JOINS - INNER JOIN
18-JOINS - LEFT JOIN
19-JOINS - RIGHT JOIN   
20-JOINS - FULL JOIN
21-VIEWS - CRIANDO VIEWS    
22-INSERINDO DADOS - INSERT INTO
23-ATUALIZANDO DADOS - UPDATE   
24-DELETANDO DADOS - DELETE
25-FUNÇÕES DE TEXTO - UPPER, LOWER, LENGTH, SUBSTRING
26-FUNÇÕES DE NÚMERO - ROUND, CEIL, FLOOR, RANDOM
27-FUNÇÕES DE DATA - NOW, AGE, EXTRACT
28-SUBQUERIES - SUBQUERIES SIMPLES
29-SUBQUERIES - SUBQUERIES CORRELACIONADAS
30-FUNCTIONS - CRIANDO FUNÇÕES SIMPLES
31-TRANSACTIONS - COMANDOS COMMIT E ROLLBACK
32-PROCEDURES - CRIANDO PROCEDURES SIMPLES  






















*/